export const FARES = {
  ANYWHERE_ZONE_1: 2.50,
  ANY_ONE_ZONE_OUTSIDE_1: 2.00,
  ANY_TWO_ZONE_INCLUDING_1: 2.00,
  ANY_TWO_ZONE_EXCLUDING_1: 2.25,
  ANY_THREE_ZONES: 3.20,
  BUS_JOURNEY: 1.80,
  MAX_POSSIBLE_FARE: 3.20,
};

export const TRANSPORT_TYPES = {
  BUS: 1,
  TUBE: 2,
};
